config/routes.rb
Rails.application.routes.draw do


  resources :subco_invoices
  resources :subco_pos
  resources :accounts
  devise_for :users
 
  root to: "accounts#index"

  
end

app/models/account.rb
class Account < ApplicationRecord
	
	has_many :sds, dependent: :destroy

	accepts_nested_attributes_for :sds, allow_destroy: true, reject_if: proc{ |att| att['number'].blank? }

	validates :name, presence: true
	

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :order

  enum milestone: [:dp, :pre_pac, :pac, :fac]

  enum status: [:raised, :uploaded, :paid]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :sd

  enum category: [:customer, :supplier, :sub_contractor]
end

app/models/sd.rb
class Sd < ApplicationRecord
  belongs_to :account, optional: true
end

app/models/subco_invoice.rb
class SubcoInvoice < ApplicationRecord
  belongs_to :subco_po
end

app/models/subco_po.rb
class SubcoPo < ApplicationRecord
  belongs_to :sd
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new

    @account.sds.build
  end

  # GET /accounts/1/edit
  def edit

    @account.sds.build
    
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :details, :sds_attributes => Sd.attribute_names.map(&:to_sym).push(:_destroy))
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subco_invoices_controller.rb
class SubcoInvoicesController < ApplicationController
  before_action :set_subco_invoice, only: [:show, :edit, :update, :destroy]

  # GET /subco_invoices
  # GET /subco_invoices.json
  def index
    @subco_invoices = SubcoInvoice.all
  end

  # GET /subco_invoices/1
  # GET /subco_invoices/1.json
  def show
  end

  # GET /subco_invoices/new
  def new
    @subco_invoice = SubcoInvoice.new
  end

  # GET /subco_invoices/1/edit
  def edit
  end

  # POST /subco_invoices
  # POST /subco_invoices.json
  def create
    @subco_invoice = SubcoInvoice.new(subco_invoice_params)

    respond_to do |format|
      if @subco_invoice.save
        format.html { redirect_to @subco_invoice, notice: 'Subco invoice was successfully created.' }
        format.json { render :show, status: :created, location: @subco_invoice }
      else
        format.html { render :new }
        format.json { render json: @subco_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subco_invoices/1
  # PATCH/PUT /subco_invoices/1.json
  def update
    respond_to do |format|
      if @subco_invoice.update(subco_invoice_params)
        format.html { redirect_to @subco_invoice, notice: 'Subco invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @subco_invoice }
      else
        format.html { render :edit }
        format.json { render json: @subco_invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subco_invoices/1
  # DELETE /subco_invoices/1.json
  def destroy
    @subco_invoice.destroy
    respond_to do |format|
      format.html { redirect_to subco_invoices_url, notice: 'Subco invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subco_invoice
      @subco_invoice = SubcoInvoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subco_invoice_params
      params.require(:subco_invoice).permit(:date, :details, :invoice_num, :amount, :subco_po_id, :milestone, :status, :pv_number, :approval)
    end
end

app/controllers/subco_pos_controller.rb
class SubcoPosController < ApplicationController
  before_action :set_subco_po, only: [:show, :edit, :update, :destroy]

  # GET /subco_pos
  # GET /subco_pos.json
  def index
    @subco_pos = SubcoPo.all
  end

  # GET /subco_pos/1
  # GET /subco_pos/1.json
  def show
  end

  # GET /subco_pos/new
  def new
    @subco_po = SubcoPo.new
  end

  # GET /subco_pos/1/edit
  def edit
  end

  # POST /subco_pos
  # POST /subco_pos.json
  def create
    @subco_po = SubcoPo.new(subco_po_params)

    respond_to do |format|
      if @subco_po.save
        format.html { redirect_to @subco_po, notice: 'Subco po was successfully created.' }
        format.json { render :show, status: :created, location: @subco_po }
      else
        format.html { render :new }
        format.json { render json: @subco_po.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subco_pos/1
  # PATCH/PUT /subco_pos/1.json
  def update
    respond_to do |format|
      if @subco_po.update(subco_po_params)
        format.html { redirect_to @subco_po, notice: 'Subco po was successfully updated.' }
        format.json { render :show, status: :ok, location: @subco_po }
      else
        format.html { render :edit }
        format.json { render json: @subco_po.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subco_pos/1
  # DELETE /subco_pos/1.json
  def destroy
    @subco_po.destroy
    respond_to do |format|
      format.html { redirect_to subco_pos_url, notice: 'Subco po was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subco_po
      @subco_po = SubcoPo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subco_po_params
      params.require(:subco_po).permit(:date, :details, :number, :amount, :sd_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subco_invoices_helper.rb
module SubcoInvoicesHelper
end

app/helpers/subco_pos_helper.rb
module SubcoPosHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :details %>
  </div>

  

  <hr>

  <div>
  	
  	<%= f.simple_fields_for :sds do |sd| %>

  		
		   <%= sd.input :number %>
		

  	<% end %>

  	<hr>

 

  </div>

   <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>


<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>


<div class="row">

  <% @accounts.each do |account| %>

    <div class="col-sm-4">
      

      <div class="card border-success mb3 m-1">
        <div class="card-header"><h6><%= account.name %></h6></div>

          <div class="card-body">

            <p><%= account.details %></p>

            <div class="btn-group">
              


            <%= link_to 'Show', account, class: "btn btn-outline-success btn-sm" %>
            <%= link_to 'Edit', edit_account_path(account), class: "btn btn-outline-warning btn-sm"  %>
            <%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm"  %>
          


            </div>

            

          </div>

        </div>
    

      </div>  
  <% end %>
</div>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header"><h6><%= @account.name %> | <%= @account.details %></h6></div>
  

   	<div >
        

       <div class="card-body">
  	
		
		  <div class="row">
		  	<% @account.sds.each do |sd| %>

		  	


		  		<div class="card border-success col-sm-2 mb3 m-1">
		  		<%= link_to root_path do %>
		  			<div class="container">
		  				<h6 class="m-1"><%=	sd.number %></h6>	
		  			</div>
		  		<% end %>
		  		</div>

		  		
	            
            <% end %>

  		   </div>


  		
    

       </div>

    </div>
    

    

  <div class="card-footer">
    	
   <%= link_to 'Edit', edit_account_path(@account), class: "btn btn-raised btn-primary" %> |
	<%= link_to 'Back', accounts_path, class: "btn btn-raised btn-success" %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
   

    <div class="container-fluid">
      <%= yield %>
    </div>

    
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer text-muted bg-light">
  <div class="container">
    <span>© <%= Date.today.year %> Sparks </span>
    <ul class="list-inline mb-0 float-right">
      <li class="list-inline-item mr-3">Terms</li>
      <li class="list-inline-item mr-3">Privacy</li>
    </ul>
  </div>
</footer>

app/views/shared/_head.html.erb
<title>Watz</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Watz", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/subco_invoices/_form.html.erb
<%= simple_form_for(@subco_invoice) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :details %>
    <%= f.input :invoice_num %>
    <%= f.input :amount %>
    <%= f.association :subco_po %>
    <%= f.input :milestone %>
    <%= f.input :status %>
    <%= f.input :pv_number %>
    <%= f.input :approval %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subco_invoices/edit.html.erb
<h1>Editing Subco Invoice</h1>

<%= render 'form', subco_invoice: @subco_invoice %>

<%= link_to 'Show', @subco_invoice %> |
<%= link_to 'Back', subco_invoices_path %>

app/views/subco_invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subco Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Details</th>
      <th>Invoice num</th>
      <th>Amount</th>
      <th>Subco po</th>
      <th>Milestone</th>
      <th>Status</th>
      <th>Pv number</th>
      <th>Approval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subco_invoices.each do |subco_invoice| %>
      <tr>
        <td><%= subco_invoice.date %></td>
        <td><%= subco_invoice.details %></td>
        <td><%= subco_invoice.invoice_num %></td>
        <td><%= subco_invoice.amount %></td>
        <td><%= subco_invoice.subco_po %></td>
        <td><%= subco_invoice.milestone %></td>
        <td><%= subco_invoice.status %></td>
        <td><%= subco_invoice.pv_number %></td>
        <td><%= subco_invoice.approval %></td>
        <td><%= link_to 'Show', subco_invoice %></td>
        <td><%= link_to 'Edit', edit_subco_invoice_path(subco_invoice) %></td>
        <td><%= link_to 'Destroy', subco_invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subco Invoice', new_subco_invoice_path %>

app/views/subco_invoices/new.html.erb
<h1>New Subco Invoice</h1>

<%= render 'form', subco_invoice: @subco_invoice %>

<%= link_to 'Back', subco_invoices_path %>

app/views/subco_invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @subco_invoice.date %>
</p>

<p>
  <strong>Details:</strong>
  <%= @subco_invoice.details %>
</p>

<p>
  <strong>Invoice num:</strong>
  <%= @subco_invoice.invoice_num %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @subco_invoice.amount %>
</p>

<p>
  <strong>Subco po:</strong>
  <%= @subco_invoice.subco_po %>
</p>

<p>
  <strong>Milestone:</strong>
  <%= @subco_invoice.milestone %>
</p>

<p>
  <strong>Status:</strong>
  <%= @subco_invoice.status %>
</p>

<p>
  <strong>Pv number:</strong>
  <%= @subco_invoice.pv_number %>
</p>

<p>
  <strong>Approval:</strong>
  <%= @subco_invoice.approval %>
</p>

<%= link_to 'Edit', edit_subco_invoice_path(@subco_invoice) %> |
<%= link_to 'Back', subco_invoices_path %>

app/views/subco_pos/_form.html.erb
<%= simple_form_for :subco_po do |f| %>

 
 

              <div class="row">
                <div class="form-label-group col-md-4 mb-3">
               
                 <%= f.input :date, as: :date, html5: true %>

                  
                  <div class="invalid-feedback">
                    Valid Task name is required.
                  </div>
                </div>
                <div class="form-label-group col-md-4 mb-3">
                  
                  <%= f.input :details, class: "form-control", value: "required"  %>
                  
                  <div class="invalid-feedback">
                    Valid Start Date is required.
                  </div>
                </div>

                  <div class="form-label-group col-md-4 mb-3">
                    
                    <%= f.input :number, class: "form-control", value: "required" %>
                    
                    <div class="invalid-feedback">
                      Valid Duration is required.
                    </div>
                </div>

                  <div class="form-label-group col-md-4 mb-3">
                    
                     <%= f.input :amount %>
                    
                    <div class="invalid-feedback">
                      Valid Duration is required.
                    </div>
                </div>
                
                  <div class="form-label-group col-md-4 mb-3">
                    
                   
                    
                    <div class="invalid-feedback">
                      Valid Duration is required.
                    </div>
                </div>
              </div>

              <%= f.button :submit, class: "btn btn-primary btn-lg btn-block"  %>
              
    

  
<% end %>

app/views/subco_pos/edit.html.erb
<h1>Editing Subco Po</h1>

<%= render 'form', subco_po: @subco_po %>

<%= link_to 'Show', @subco_po %> |
<%= link_to 'Back', subco_pos_path %>

app/views/subco_pos/index.html.erb
<p id="notice"><%= notice %></p>



<br>

<%= link_to 'New Subco Po', new_subco_po_path %>

<div>

      <div role="main" class="container1">
        <div class="jumbotron text-center">
          <h1>Project Title</h1>
          <div class="row">
              <div class="col-md-2 mb-3">
                <a href="#">
                  <h1><i class="fas fa-angle-double-left"></i></h1>
                </a>
              </div>
              <div class="col-md-8 mb-3">
                <h2>Site name</h2>
                <h3>Site ID</h3>
                <button class="btn btn-outline-success btn-lg btn-block" type="submit">All Sites</button>
              </div>
              <div class="col-md-2 mb-3">
                <a href="#">
                  <h1><i class="fas fa-angle-double-right"></i></h1>
                </a>
              </div>
            </div>
          </div>
      </div>


    <div class="container">
      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Project Health</span>
            <span class="badge badge-secondary badge-pill">Status:</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Project Status</h6>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
                </div>
              </div>
              <span class="text-muted"></span>
            </li>

            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Current Activity</h6>
                <small class="text-muted">Start date: </small>
                <br>
                <small class="text-muted">Due date:</small>
              </div>
              <span class="text-muted">
                <div>
                  <span class="badge badge-secondary badge-pill">Status</span>
                </div>
              </span>
            </li>

            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Tasks Status</h6>
                <div>
                  <small class="text-muted">Open tasks:</small>
                  <span class="badge badge-secondary badge-pill">3</span>
                </div>

                <div>
                  <small class="text-muted">closed tasks:</small>
                  <span class="badge badge-secondary badge-pill">4</span>
                </div>
                <div>
                  <small class="text-muted">Overdue tasks:</small>
                  <span class="badge badge-secondary badge-pill">5</span>
                </div>
              </div>
            </li>
          </ul>
        </div>
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Subco Pos</h4>
          <hr class="mb-4">
          <div class="row">

             <div class="form-inputs">
    
                <form>

                  <%= render 'form', subco_po: @subco_po %>
                  
                </form>
              </div>

          </div>
          <div class="row">


            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Details</th>
                  <th>Number</th>
                  <th>Amount</th>
                  <th>Sd</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @subco_pos.each do |subco_po| %>
                  <tr>
                    <td><%= subco_po.date %></td>
                    <td><%= subco_po.details %></td>
                    <td><%= subco_po.number %></td>
                    <td><%= subco_po.amount %></td>
                    <td><%= subco_po.sd %></td>
                    <td><%= link_to 'Show', subco_po %></td>
                    <td><%= link_to 'Edit', edit_subco_po_path(subco_po) %></td>
                    <td><%= link_to 'Destroy', subco_po, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>


          </div>
        </div>
        </div>
      </div>

  </div>

app/views/subco_pos/new.html.erb
<h1>New Subco Po</h1>

<%= render 'form', subco_po: @subco_po %>

<%= link_to 'Back', subco_pos_path %>

app/views/subco_pos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @subco_po.date %>
</p>

<p>
  <strong>Details:</strong>
  <%= @subco_po.details %>
</p>

<p>
  <strong>Number:</strong>
  <%= @subco_po.number %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @subco_po.amount %>
</p>

<p>
  <strong>Sd:</strong>
  <%= @subco_po.sd %>
</p>

<%= link_to 'Edit', edit_subco_po_path(@subco_po) %> |
<%= link_to 'Back', subco_pos_path %>